
# options.cmake
# CC_PLATFORM_OPTIONS
if(CC_TARGET_LINUX)
    add_compile_definitions(CC_TARGET_LINUX=1)
elseif(CC_TARGET_MACOS)
    add_compile_definitions(CC_TARGET_MACOS=1)
elseif(CC_TARGET_IOS)
    add_compile_definitions(CC_TARGET_IOS=1)
elseif(CC_TARGET_ANDROID)
    add_compile_definitions(CC_TARGET_ANDROID=1)
elseif(CC_TARGET_WINDOWS)
    add_compile_definitions(CC_TARGET_WINDOWS=1)
elseif(CC_TARGET_WASM)
    add_compile_definitions(CC_TARGET_WASM=1)
elseif(CC_TARGET_T113)
    add_compile_definitions(CC_TARGET_T113=1)
elseif(CC_TARGET_H616)
    add_compile_definitions(CC_TARGET_H616=1)
elseif(CC_TARGET_T113_S3)
    add_compile_definitions(CC_TARGET_T113_S3=1)
elseif(CC_TARGET_T113_I)
    add_compile_definitions(CC_TARGET_T113_I=1)
elseif(CC_TARGET_SSD202)
    add_compile_definitions(CC_TARGET_SSD202=1)
elseif(CC_TARGET_SSD212)
    add_compile_definitions(CC_TARGET_SSD212=1)
elseif(CC_TARGET_JNI_LINUX)
    add_compile_definitions(CC_TARGET_JNI_LINUX=1)
elseif(CC_TARGET_JNI_WINDOWS)
    add_compile_definitions(CC_TARGET_JNI_WINDOWS=1)
elseif(CC_TARGET_JNI_MACOS)
    add_compile_definitions(CC_TARGET_JNI_MACOS=1)
elseif(CC_TARGET_ESP32)
    add_compile_definitions(CC_TARGET_ESP32=1)
elseif(CC_TARGET_ESP8266)
    add_compile_definitions(CC_PLATFORM_ESP8266=1)
endif()
    